[features]
seeds = false
skip-lint = false

[programs.localnet]
sonic_svm = "9Lh2tuGKdbVMfmFFEeGDix45cfnNHZzi5mNsseaexuVR"

[programs.testnet]
sonic_svm = "9Lh2tuGKdbVMfmFFEeGDix45cfnNHZzi5mNsseaexuVR"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "testnet"
wallet = "~/.config/solana/id.json"

[provider.testnet]
url = "https://api.testnet.sonic.game"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts" 